;;; related-files-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from related-files.el

(autoload 'sstoltze/related-files "related-files" "\
Return a list of (name . path) annotations for the current buffer." t)
(autoload 'sstoltze/find-related-file "related-files" "\
Let's try this thing out." t)
(register-definition-prefixes "related-files" '("sstoltze/line-end-respecting-backslash"))

;;; End of scraped data

(provide 'related-files-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; related-files-autoloads.el ends here
